### ISSUE TITLE
Configuring middleware

### ISSUE THREAD

**Issue by southekal** [randysecrist/connect-riak-sessions#2]
var RiakStore = require('connect-riak-sessions')(express);

// Configure Middleware
app.use(express.session({
  store: new RiakSessionStore({ // change RiakSessionStore to RiakStore?
    bucket: 'app_session_bucket',
    scheme: 'http',
    host: 'localhost',
    port: 8098,
  }),
  secret: 'keyboard cat'
}));

**Comment by randysecrist** [comment]
use version 0.0.3 to make it work with express-session.
